A0-1361: set session keys check
Cardinal-Cryptography/aleph-node-runner pull request #23
Opened 2022-09-19 09:12 UTC by krzysztofziobro

Adds a session key check to `run_node.sh`:
- When run as a validator it takes mandatory `--stash_account` argument
- Checks if session keys are set for this stash account - uses `cliain`
- If there are, then makes an RPC call to the node, checking if node has access to the keys.
- If not, it will stop the node and print an error.

2022-09-20 06:10 UTC, Marcin-Radecki requested changes
Solid job, just minor comments

2022-09-20 08:31 UTC, krzysztofziobro commented on run_node.sh
> +if [[ -n "$SESSION_KEYS_JSON" ]]
The case in which there are no keys set for the account will be handled in the next PR. But I can add a small echo for now, I guess.

2022-09-22 05:18 UTC, Marcin-Radecki approved these changes
Nice!

2022-09-23 10:32 UTC, piotrMocz reviewed
Cool! I'd consider making the `stash_account` argument mandatory -- right now the `usage` docstring suggests it's optional.

As a sidenote, I generally like to reference variables as `${VAR}` -- in some cases it can save you some surprises.

2022-09-23 10:32 UTC, piotrMocz commented on run_node.sh
> +    STASH_ACCOUNT=${STASH_ACCOUNT:?'Please specify your stash account_id.'}
Maybe we should make this argument mandatory and reflect this in the `usage` docstring?

2022-09-23 10:32 UTC, piotrMocz commented on run_node.sh
> +    echo 'Node run as archivist: no need to check session keys.'
We might (and this is mostly thinking out loud) want to replace the 'archivist' with 'rpc node', the name archivist is a little misleading

2022-10-03 10:04 UTC, piotrMocz approved these changes
Great! One more ask though: could also add the new argument to the README?

2022-10-17 09:13 UTC, merged